# Generated by Django 4.1.7 on 2023-02-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_arrivee', models.DateField()),
                ('date_depart', models.DateField()),
                ('nombre_personnes', models.IntegerField()),
            ],
        ),
    ]
