# Generated by Django 4.1.7 on 2023-03-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appResa', '0002_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='nom_ecole',
            field=models.IntegerField(default=4),
        ),
    ]
